// lib/photoTemplate.ts
export type PhotoInputType = "photo" | "photo+sn" | "photo+cable";
export interface PhotoTemplateItem {
  id: string;
  name: string;
  type: PhotoInputType;
  sort: number;
}
export const PHOTO_TEMPLATE: PhotoTemplateItem[] = [
  { id: "1", name: "Fisik CCTV", type: "photo", sort: 1 },
  { id: "2", name: "Foto Terpasang CCTV 1", type: "photo", sort: 2 },
  { id: "3", name: "S/N CCTV 1", type: "photo+sn", sort: 3 },
  { id: "4", name: "Foto Terpasang CCTV 2", type: "photo", sort: 4 },
  { id: "5", name: "S/N CCTV 2", type: "photo+sn", sort: 5 },
  { id: "6", name: "Foto Terpasang CCTV 3", type: "photo", sort: 6 },
  { id: "7", name: "S/N CCTV 3", type: "photo+sn", sort: 7 },
  { id: "8", name: "Foto Terpasang CCTV 4", type: "photo", sort: 8 },
  { id: "9", name: "S/N CCTV 4", type: "photo+sn", sort: 9 },
  { id: "10", name: "Fisik Switch", type: "photo", sort: 10 },
  { id: "11", name: "S/N Switch", type: "photo+sn", sort: 11 },
  { id: "12", name: "Foto Terpasang Switch", type: "photo", sort: 12 },
  { id: "13", name: "Fisik NVR", type: "photo", sort: 13 },
  { id: "14", name: "S/N NVR", type: "photo+sn", sort: 14 },
  { id: "15", name: "NVR Terpasang", type: "photo", sort: 15 },
  { id: "16", name: "Fisik Router", type: "photo", sort: 16 },
  { id: "17", name: "S/N Router", type: "photo+sn", sort: 17 },
  { id: "18", name: "Router Terpasang", type: "photo", sort: 18 },
  { id: "19", name: "Fisik Monitor", type: "photo", sort: 19 },
  { id: "20", name: "S/N Monitor", type: "photo+sn", sort: 20 },
  { id: "21", name: "Monitor Terpasang", type: "photo", sort: 21 },
  { id: "22", name: "Fisik Hard Disk", type: "photo", sort: 22 },
  { id: "23", name: "S/N Hard Disk", type: "photo+sn", sort: 23 },
  { id: "24", name: "Hard Disk Terpasang", type: "photo", sort: 24 },
  { id: "25", name: "Foto Fisik Connector RJ 45", type: "photo", sort: 25 },
  { id: "26", name: "RJ 45 Terpasang", type: "photo", sort: 26 },
  { id: "27", name: "Fisik LAN SFTP", type: "photo", sort: 27 },
  { id: "28", name: "Kabel Cam 1 (Before)", type: "photo+cable", sort: 28 },
  { id: "29", name: "Kabel Cam 1 (After)", type: "photo+cable", sort: 29 },
  { id: "30", name: "Kabel Cam 2 (Before)", type: "photo+cable", sort: 30 },
  { id: "31", name: "Kabel Cam 2 (After)", type: "photo+cable", sort: 31 },
  { id: "32", name: "Kabel Cam 3 (Before)", type: "photo+cable", sort: 32 },
  { id: "33", name: "Kabel Cam 3 (After)", type: "photo+cable", sort: 33 },
  { id: "34", name: "Kabel Cam 4 (Before)", type: "photo+cable", sort: 34 },
  { id: "35", name: "Kabel Cam 4 (After)", type: "photo+cable", sort: 35 },
  { id: "36", name: "Kabel NVR (before)", type: "photo+cable", sort: 36 },
  { id: "37", name: "Kabel NVR (After)", type: "photo+cable", sort: 37 },
  { id: "38", name: "Fisik Kabel NYM", type: "photo", sort: 38 },
  { id: "39", name: "Kabel NYM Terpasang", type: "photo", sort: 39 },
  { id: "40", name: "Fisik Duradus Masko", type: "photo", sort: 40 },
  { id: "41", name: "Duradus Masko Terpasang", type: "photo", sort: 41 },
  { id: "42", name: "Fisik Box Panel Outdoor", type: "photo", sort: 42 },
  { id: "43", name: "Box Panel Terpasang", type: "photo", sort: 43 },
  { id: "44", name: "Fisik Steker Arde Uticon", type: "photo", sort: 44 },
  { id: "45", name: "Steker Terpasang", type: "photo", sort: 45 },
  { id: "46", name: "Fisik Stop Kontak Outbow", type: "photo", sort: 46 },
  { id: "47", name: "Stop Kontak Terpasang", type: "photo", sort: 47 },
  { id: "48", name: "Fisik Kabel Twisted", type: "photo", sort: 48 },
  { id: "49", name: "Kabel Twisted Terpasang", type: "photo", sort: 49 },
  { id: "50", name: "Foto Proses Instalasi Cam 1", type: "photo", sort: 50 },
  { id: "51", name: "Foto Proses Instalasi Cam 2", type: "photo", sort: 51 },
  { id: "52", name: "Foto Proses Instalasi Cam 3", type: "photo", sort: 52 },
  { id: "53", name: "Foto Proses Instalasi Cam 4", type: "photo", sort: 53 },
  { id: "54", name: "View Keseluruhan", type: "photo", sort: 54 },
  { id: "55", name: "Pelatihan", type: "photo", sort: 55 },
];